### PR TITLE
Added navigation panel

### PR DESCRIPTION
**Pull request by hunteroone**
This adds a basic navigation pane to each section of the website and also added a marquee to the wiki.

### CODE REVIEW

**Comment by 5KS** [comment]
https://www.w3schools.com/html/html_head.asp

pre' do not belong to head'.

please sir, do not justify the bloatness of the browsers.
i've only 4gb of ram to run.

**Comment by NoSJW** [comment]
Good advice, but the wiki does need internal navigation of some kind, if only to link back to the writs section on every page.

**Comment by 5KS** [comment]
head
  pre
head

->

head
head
pre

btw, https://alpinelinux.org has a pure html navigation, and a hamburger menu.

**Comment by hunteroone** [comment]
> pre' do not belong to head'.

Pre is preformatted text. Its in head because the navbar is not part of the body.

> please sir, do not justify the bloatness of the browsers.
> i've only 4gb of ram to run.

Are you talking about marquee? Its been a feature since web 1.0.

**Comment by 5KS** [comment]
maybe i was too convinced that head should contain only meta.

**Pull request closed without merging**
